version: '3' #docker-compose 지원버전
services:
  application:
    container_name: container-test
    image: kangjunho/keyappsk:v6
    volumes:
      - storeImage:/var/keyAppsk/storeImage
      - productImage:/var/keyAppsk/productImage
    env_file:
      - .env
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8080:8080" # host: docker

volumes:
  storeImage:
    external: true
  productImage:
    external: true