spring:
  application:
    name: keyAppsk
  profiles:
    include: oauth
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #local환경
#    url: jdbc:mysql://localhost:3306/keyAppsk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    docker 환경
#    url: jdbc:mysql://mysql-container:3306/keyAppsk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    username: root #local, docker
    #    password: 1234 #local. docker
    # rds 환경
    url: ${RDS_KEYAPPSK_URL}
    username: ${RDS_KEYAPPSK_USERNAME} # rds
    password: ${RDS_KEYAPPSK_PASSWORD} # rds

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  servlet:
    session:
      tracking-modes : cookie
