#oauth2
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE-CLIENT-ID}
            client-secret: ${GOOGLE-CLIENT-SECRET}
            scope:
              - profile
              - email
          naver:
            client-id: ${NAVER-CLIENT-ID}
            client-secret: ${NAVER-CLIENT-SECRET}
            redirect-uri: ${NAVER-REDIRECT-URI}
            authorization-grant-type: authorization_code
            scope : name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response